Add TMTQUant parser and fix flashLFQ
computational-ms/pyiohat pull request #37
Opened 2023-03-22 10:46 UTC by MKoesters

- add TMTQuant parser
- add tests for TMTQuant parser
- add test files for TMTQuant parser
- activate `sanitize` in quant_base_parser
- fix issues in FlashLFQ parser

2023-03-23 10:53 UTC, fu commented on pyiohat/parsers/quant/tmt_quant_parser_1_0_0.py
> +        # }
del diz :)

2023-03-23 10:55 UTC, fu commented on tests/data/TMT16_ursgal_lookup.csv
> +lineage_root,file,spectrum_id,ms_level,rt,rt_unit,preset_scan_configuration,total_ion_current,ion_injection_time,ion_injection_time_unit,filter_string,scan_window_lower_limit,scan_window_upper_limit,
lineage_root is a ursgal concept and should not be used / imposed / confuse people outside of ursgal. Maybe rename it (back?) to raw_data_location

2023-03-23 10:56 UTC, fu requested changes
Column needs to be renamed, see comment

2023-03-27 14:47 UTC, tristan-ranff approved these changes

2023-03-27 14:47 UTC, merged